INCLUDES += -I$(RIOTBOARD)/common/arduino-atmega/include

include $(RIOTMAKE)/tools/serial.inc.mk

# include avrdude flashing tool
include $(RIOTMAKE)/tools/avrdude.inc.mk
include $(RIOTBOARD)/common/atmega/Makefile.include
