include ../Makefile.tests_common

USEMODULE += auto_init_gnrc_netif
USEMODULE += auto_init_ptp_client
USEMODULE += gnrc
USEMODULE += gnrc_icmpv6_echo
USEMODULE += gnrc_icmpv6_error
USEMODULE += gnrc_ipv6_router_default
USEMODULE += netdev_default
USEMODULE += netstats_ipv6
USEMODULE += netstats_l2
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
